RESTORE HEADERONLY FROM DISK = 'C:\SQL\oj9.bak'

RESTORE DATABASE group9_project FROM DISK = 'C:\SQL\oj9.bak'
WITH NORECOVERY,
FILE = 4
GO

RESTORE DATABASE group9_project FROM DISK = 'C:\SQL\oj9.bak'
WITH NORECOVERY,
FILE = 8
GO

RESTORE LOG group9_project FROM DISK = 'C:\SQL\oj9.bak'
WITH NORECOVERY,
FILE = 9
GO

RESTORE LOG group9_project FROM DISK = 'C:\SQL\oj9.bak'
WITH RECOVERY,
FILE = 10,
STOPAT = '2018-03-08 19:43:37'
GO
